# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift5GoogleAdmb1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for Swift5GoogleAdmb1
pod 'Google-Mobile-Ads-SDK'

end
