# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift5Bokete2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift5Bokete2
pod 'SwiftyJSON'
pod 'Alamofire', '~> 5.0.0-rc.3'
pod 'SDWebImage'

end
